// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  $(function() {
    app.setBind();
    return app.initialize();
  });

  app = {
    initialize: function() {
      this.setModal();
      return this.clearModal();
    },
    setBind: function() {
      return this.scrolPageAnchor();
    },
    scrolPageAnchor: function() {
      $('a[href^=#]').click(function() {
        var href, position, speed, target;
        console.log('A');
        speed = 500;
        href = $(this).attr('href');
        target = $(href === '#' || href === '' ? 'html' : href);
        position = target.offset().top;
        $('body,html').animate({
          scrollTop: position
        }, speed, 'swing');
        return false;
      });
    },
    setModal: function() {
      $('.like').click(function() {
        $('#modal-overlay').fadeIn(500);
        return $('.modal-like').fadeIn(500);
      });
      $('.skill').click(function() {
        $('#modal-overlay').fadeIn(500);
        return $('.modal-skill').fadeIn(500);
      });
      $('.strength').click(function() {
        $('#modal-overlay').fadeIn(500);
        return $('.modal-strength').fadeIn(500);
      });
      $('.character').click(function() {
        $('#modal-overlay').fadeIn(500);
        return $('.modal-character').fadeIn(500);
      });
      $('.hobby').click(function() {
        $('#modal-overlay').fadeIn(500);
        return $('.modal-hobby').fadeIn(500);
      });
      $('.dream').click(function() {
        $('#modal-overlay').fadeIn(500);
        return $('.modal-dream').fadeIn(500);
      });
      $('.blog').click(function() {
        $('#modal-overlay').fadeIn(500);
        return $('.modal-blog').fadeIn(500);
      });
      return $('.sns').click(function() {
        $('#modal-overlay').fadeIn(500);
        return $('.modal-sns').fadeIn(500);
      });
    },
    clearModal: function() {
      $('#modal-overlay').click(function() {
        $('#modal-overlay').fadeOut(500);
        return $('.modal-contents').fadeOut(500);
      });
      return $('.modal-button-close').click(function() {
        $('#modal-overlay').fadeOut(500);
        return $('.modal-contents').fadeOut(500);
      });
    },
    hoverContentsAnimate: function() {
      $('.like').hover(function() {
        $('.like-slide').stop().animate({
          "width": "100%"
        }, 500);
        return $('.like-title').stop().animate({
          "color": "#ffffff"
        }, 500);
      }, function() {
        $('.like-slide').stop().animate({
          "width": "0%"
        }, 500);
        return $('.like-title').stop().animate({
          "color": "#28C694"
        }, 500);
      });
      $('.skill').hover(function() {
        $('.skill-slide').stop().animate({
          "width": "100%"
        }, 500);
        return $('.skill-title').stop().animate({
          "color": "#ffffff"
        }, 500);
      }, function() {
        $('.skill-slide').stop().animate({
          "width": "0%"
        }, 500);
        return $('.skill-title').stop().animate({
          "color": "#35A5E5"
        }, 500);
      });
      $('.strength').hover(function() {
        $('.strength-slide').stop().animate({
          "width": "100%"
        }, 500);
        return $('.strength-title').stop().animate({
          "color": "#ffffff"
        }, 500);
      }, function() {
        $('.strength-slide').stop().animate({
          "width": "0%"
        }, 500);
        return $('.strength-title').stop().animate({
          "color": "#F28E4A"
        }, 500);
      });
      $('.character').hover(function() {
        $('.character-slide').stop().animate({
          "width": "100%"
        }, 500);
        return $('.character-title').stop().animate({
          "color": "#ffffff"
        }, 500);
      }, function() {
        $('.character-slide').stop().animate({
          "width": "0%"
        }, 500);
        return $('.character-title').stop().animate({
          "color": "#ff4761"
        }, 500);
      });
      $('.hobby').hover(function() {
        $('.hobby-slide').stop().animate({
          "width": "100%"
        }, 500);
        return $('.hobby-title').stop().animate({
          "color": "#ffffff"
        }, 500);
      }, function() {
        $('.hobby-slide').stop().animate({
          "width": "0%"
        }, 500);
        return $('.hobby-title').stop().animate({
          "color": "#ff4761"
        }, 500);
      });
      $('.dream').hover(function() {
        $('.dream-slide').stop().animate({
          "width": "100%"
        }, 500);
        return $('.dream-title').stop().animate({
          "color": "#ffffff"
        }, 500);
      }, function() {
        $('.dream-slide').stop().animate({
          "width": "0%"
        }, 500);
        return $('.dream-title').stop().animate({
          "color": "#F28E4A"
        }, 500);
      });
      $('.blog').hover(function() {
        $('.blog-slide').stop().animate({
          "width": "100%"
        }, 500);
        return $('.blog-title').stop().animate({
          "color": "#ffffff"
        }, 500);
      }, function() {
        $('.blog-slide').stop().animate({
          "width": "0%"
        }, 500);
        return $('.blog-title').animate({
          "color": "#35A5E5"
        }, 500);
      });
      return $('.sns').hover(function() {
        $('.sns-slide').stop().animate({
          "width": "100%"
        }, 500);
        return $('.sns-title').stop().animate({
          "color": "#ffffff"
        }, 500);
      }, function() {
        $('.sns-slide').stop().animate({
          "width": "0%"
        }, 500);
        return $('.sns-title').stop().animate({
          "color": "#28C694"
        }, 500);
      });
    }
  };

}).call(this);
